import abjad
import ide

persist = abjad.OrderedDict(
    [
        (
            "alive_during_segment",
            [
                "Score",
                "Global_Context",
                "Global_Skips",
                "Music_Context",
                "Wind_Section_Staff_Group",
                "Bass_Flute_Music_Staff",
                "Global_Rests",
                "Bass_Flute_Music_Voice",
                "Bass_Flute_Rest_Voice",
                "Percussion_Section_Staff_Group",
                "Percussion_I_Music_Staff",
                "Percussion_I_Music_Voice",
                "Percussion_I_Rest_Voice",
                "Percussion_II_Music_Staff",
                "Percussion_II_Music_Voice",
                "Percussion_II_Rest_Voice",
                "Harp_Music_Staff",
                "Harp_Music_Voice",
                "Harp_Rest_Voice",
                "String_Section_Staff_Group",
                "Viola_Music_Staff",
                "Viola_Music_Voice",
                "Viola_Rest_Voice",
                "Cello_I_Music_Staff",
                "Cello_I_Music_Voice",
                "Cello_I_Rest_Voice",
                "Cello_II_Music_Staff",
                "Cello_II_Music_Voice",
                "Cello_II_Rest_Voice",
                "Contrabass_I_Music_Staff",
                "Contrabass_I_Music_Voice",
                "Contrabass_I_Rest_Voice",
                "Contrabass_II_Music_Staff",
                "Contrabass_II_Music_Voice",
                "Contrabass_II_Rest_Voice",
            ],
        ),
        (
            "persistent_indicators",
            abjad.OrderedDict(
                [
                    (
                        "Bass_Flute_Music_Staff",
                        [
                            ide.Momento(
                                context="Bass_Flute_Music_Voice",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Bfl.",
                            ),
                            ide.Momento(
                                context="Bass_Flute_Music_Voice",
                                manifest="instruments",
                                value="BassFlute",
                            ),
                            ide.Momento(
                                context="Bass_Flute_Music_Voice",
                                prototype="abjad.Clef",
                                value="treble",
                            ),
                            ide.Momento(
                                context="Bass_Flute_Music_Voice",
                                prototype="baca.BarExtent",
                                value=5,
                            ),
                            ide.Momento(
                                context="Bass_Flute_Music_Voice",
                                prototype="baca.StaffLines",
                                value=5,
                            ),
                        ],
                    ),
                    (
                        "Bass_Flute_Music_Voice",
                        [
                            ide.Momento(
                                context="Bass_Flute_Music_Voice",
                                prototype="abjad.Dynamic",
                                value="\\baca-mf-sempre",
                            ),
                        ],
                    ),
                    (
                        "Cello_II_Music_Staff",
                        [
                            ide.Momento(
                                context="Cello_II_Music_Voice",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vc. II",
                            ),
                            ide.Momento(
                                context="Cello_II_Music_Voice",
                                manifest="instruments",
                                value="Cello",
                            ),
                            ide.Momento(
                                context="Cello_II_Music_Voice",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                            ide.Momento(
                                context="Cello_II_Music_Voice",
                                prototype="baca.BarExtent",
                                value=5,
                            ),
                            ide.Momento(
                                context="Cello_II_Music_Voice",
                                prototype="baca.StaffLines",
                                value=5,
                            ),
                        ],
                    ),
                    (
                        "Cello_II_Music_Voice",
                        [
                            ide.Momento(
                                context="Cello_II_Music_Voice",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Cello_I_Music_Staff",
                        [
                            ide.Momento(
                                context="Cello_I_Music_Voice",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Vc. I",
                            ),
                            ide.Momento(
                                context="Cello_I_Music_Voice",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=5,
                            ),
                            ide.Momento(
                                context="Cello_I_Music_Voice",
                                manifest="instruments",
                                value="Cello",
                            ),
                            ide.Momento(
                                context="Cello_I_Music_Voice",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                            ide.Momento(
                                context="Cello_I_Music_Voice",
                                prototype="baca.StaffLines",
                                value=5,
                            ),
                        ],
                    ),
                    (
                        "Cello_I_Music_Voice",
                        [
                            ide.Momento(
                                context="Cello_I_Music_Voice",
                                prototype="abjad.Dynamic",
                                value="mf",
                            ),
                        ],
                    ),
                    (
                        "Contrabass_II_Music_Staff",
                        [
                            ide.Momento(
                                context="Contrabass_II_Music_Voice",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Cb. II",
                            ),
                            ide.Momento(
                                context="Contrabass_II_Music_Voice",
                                manifest="instruments",
                                value="Contrabass",
                            ),
                            ide.Momento(
                                context="Contrabass_II_Music_Voice",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                            ide.Momento(
                                context="Contrabass_II_Music_Voice",
                                prototype="baca.BarExtent",
                                value=5,
                            ),
                            ide.Momento(
                                context="Contrabass_II_Music_Voice",
                                prototype="baca.StaffLines",
                                value=5,
                            ),
                        ],
                    ),
                    (
                        "Contrabass_II_Music_Voice",
                        [
                            ide.Momento(
                                context="Contrabass_II_Music_Voice",
                                prototype="abjad.Dynamic",
                                value="niente",
                            ),
                        ],
                    ),
                    (
                        "Contrabass_I_Music_Staff",
                        [
                            ide.Momento(
                                context="Contrabass_I_Music_Voice",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Cb. I",
                            ),
                            ide.Momento(
                                context="Contrabass_I_Music_Voice",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Contrabass_I_Music_Voice",
                                manifest="instruments",
                                value="Contrabass",
                            ),
                            ide.Momento(
                                context="Contrabass_I_Music_Voice",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Contrabass_I_Music_Voice",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Contrabass_I_Music_Voice",
                        [
                            ide.Momento(
                                context="Contrabass_I_Music_Voice",
                                prototype="abjad.Dynamic",
                                value="ppp",
                            ),
                        ],
                    ),
                    (
                        "Harp_Music_Staff",
                        [
                            ide.Momento(
                                context="Harp_Music_Voice",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Hp.",
                            ),
                            ide.Momento(
                                context="Harp_Music_Voice",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                            ide.Momento(
                                context="Harp_Music_Voice",
                                prototype="baca.BarExtent",
                                value=5,
                            ),
                            ide.Momento(
                                context="Harp_Music_Voice",
                                prototype="baca.StaffLines",
                                value=5,
                            ),
                        ],
                    ),
                    (
                        "Harp_Music_Voice",
                        [
                            ide.Momento(
                                context="Harp_Music_Voice",
                                prototype="abjad.Dynamic",
                                value="f",
                            ),
                        ],
                    ),
                    (
                        "Percussion_II_Music_Staff",
                        [
                            ide.Momento(
                                context="Percussion_II_Music_Voice",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Perc. II",
                            ),
                            ide.Momento(
                                context="Percussion_II_Music_Voice",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=3,
                            ),
                            ide.Momento(
                                context="Percussion_II_Music_Voice",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            ide.Momento(
                                context="Percussion_II_Music_Voice",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Percussion_II_Music_Voice",
                                prototype="baca.StaffLines",
                                value=3,
                            ),
                        ],
                    ),
                    (
                        "Percussion_II_Music_Voice",
                        [
                            ide.Momento(
                                context="Percussion_II_Music_Voice",
                                prototype="abjad.Dynamic",
                                value="f",
                            ),
                        ],
                    ),
                    (
                        "Percussion_I_Music_Staff",
                        [
                            ide.Momento(
                                context="Percussion_I_Music_Voice",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Perc. I",
                            ),
                            ide.Momento(
                                context="Percussion_I_Music_Voice",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=3,
                            ),
                            ide.Momento(
                                context="Percussion_I_Music_Voice",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            ide.Momento(
                                context="Percussion_I_Music_Voice",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Percussion_I_Music_Voice",
                                prototype="baca.StaffLines",
                                value=3,
                            ),
                        ],
                    ),
                    (
                        "Percussion_I_Music_Voice",
                        [
                            ide.Momento(
                                context="Percussion_I_Music_Voice",
                                prototype="abjad.Dynamic",
                                value="f",
                            ),
                        ],
                    ),
                    (
                        "Percussion_Section_Staff_Group",
                        [
                            ide.Momento(
                                context="Harp_Music_Voice",
                                manifest="instruments",
                                value="Harp",
                            ),
                        ],
                    ),
                    (
                        "Score",
                        [
                            ide.Momento(
                                context="Global_Skips",
                                manifest="metronome_marks",
                                value="57 3/5",
                            ),
                            ide.Momento(
                                context="Global_Skips",
                                prototype="abjad.TimeSignature",
                                value="3/4",
                            ),
                        ],
                    ),
                    (
                        "Viola_Music_Staff",
                        [
                            ide.Momento(
                                context="Viola_Music_Voice",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="Va.",
                            ),
                            ide.Momento(
                                context="Viola_Music_Voice",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=1,
                            ),
                            ide.Momento(
                                context="Viola_Music_Voice",
                                manifest="instruments",
                                value="Viola",
                            ),
                            ide.Momento(
                                context="Viola_Music_Voice",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="Viola_Music_Voice",
                                prototype="baca.StaffLines",
                                value=1,
                            ),
                        ],
                    ),
                    (
                        "Viola_Music_Voice",
                        [
                            ide.Momento(
                                context="Viola_Music_Voice",
                                prototype="abjad.Dynamic",
                                value="ppp",
                            ),
                        ],
                    ),
                ]
            ),
        ),
    ]
)
