import abjad


persist = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Skips',
                'Music_Context',
                'Wind_Section_Staff_Group',
                'Bass_Flute_Music_Staff',
                'Global_Rests',
                'Bass_Flute_Music_Voice',
                'Bass_Flute_Rest_Voice',
                'Percussion_Section_Staff_Group',
                'Percussion_I_Music_Staff',
                'Percussion_I_Music_Voice',
                'Percussion_I_Rest_Voice',
                'Percussion_II_Music_Staff',
                'Percussion_II_Music_Voice',
                'Percussion_II_Rest_Voice',
                'Harp_Music_Staff',
                'Harp_Music_Voice',
                'Harp_Rest_Voice',
                'String_Section_Staff_Group',
                'Viola_Music_Staff',
                'Viola_Music_Voice',
                'Viola_Rest_Voice',
                'Cello_I_Music_Staff',
                'Cello_I_Music_Voice',
                'Cello_I_Rest_Voice',
                'Cello_II_Music_Staff',
                'Cello_II_Music_Voice',
                'Cello_II_Rest_Voice',
                'Contrabass_I_Music_Staff',
                'Contrabass_I_Music_Voice',
                'Contrabass_I_Rest_Voice',
                'Contrabass_II_Music_Staff',
                'Contrabass_II_Music_Voice',
                'Contrabass_II_Rest_Voice',
                ],
            ),
        (
            'persistent_indicators',
            abjad.OrderedDict(
                [
                    (
                        'Bass_Flute_Music_Staff',
                        [
                            abjad.Momento(
                                context='Bass_Flute_Music_Voice',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='Bfl.',
                                ),
                            abjad.Momento(
                                context='Bass_Flute_Music_Voice',
                                manifest='instruments',
                                value='BassFlute',
                                ),
                            abjad.Momento(
                                context='Bass_Flute_Music_Voice',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            ],
                        ),
                    (
                        'Bass_Flute_Music_Voice',
                        [
                            abjad.Momento(
                                context='Bass_Flute_Music_Voice',
                                prototype='abjad.Dynamic',
                                value='\\baca-f-ancora',
                                ),
                            ],
                        ),
                    (
                        'Cello_II_Music_Staff',
                        [
                            abjad.Momento(
                                context='Cello_II_Music_Voice',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='Vc. II',
                                ),
                            abjad.Momento(
                                context='Cello_II_Music_Voice',
                                manifest='instruments',
                                value='Cello',
                                ),
                            abjad.Momento(
                                context='Cello_II_Music_Voice',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='Cello_II_Music_Voice',
                                prototype='baca.StaffLines',
                                value=5,
                                ),
                            ],
                        ),
                    (
                        'Cello_II_Music_Voice',
                        [
                            abjad.Momento(
                                context='Cello_II_Music_Voice',
                                prototype='abjad.Dynamic',
                                value='mp',
                                ),
                            ],
                        ),
                    (
                        'Cello_I_Music_Staff',
                        [
                            abjad.Momento(
                                context='Cello_I_Music_Voice',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='Vc. I',
                                ),
                            abjad.Momento(
                                context='Cello_I_Music_Voice',
                                manifest='instruments',
                                value='Cello',
                                ),
                            abjad.Momento(
                                context='Cello_I_Music_Voice',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='Cello_I_Music_Voice',
                                prototype='baca.StaffLines',
                                value=5,
                                ),
                            ],
                        ),
                    (
                        'Cello_I_Music_Voice',
                        [
                            abjad.Momento(
                                context='Cello_I_Music_Voice',
                                prototype='abjad.Dynamic',
                                value='mp',
                                ),
                            ],
                        ),
                    (
                        'Contrabass_II_Music_Staff',
                        [
                            abjad.Momento(
                                context='Contrabass_II_Music_Voice',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='Cb. II',
                                ),
                            abjad.Momento(
                                context='Contrabass_II_Music_Voice',
                                manifest='instruments',
                                value='Contrabass',
                                ),
                            abjad.Momento(
                                context='Contrabass_II_Music_Voice',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            ],
                        ),
                    (
                        'Contrabass_II_Music_Voice',
                        [
                            abjad.Momento(
                                context='Contrabass_II_Music_Voice',
                                prototype='abjad.Dynamic',
                                value='p',
                                ),
                            ],
                        ),
                    (
                        'Contrabass_I_Music_Staff',
                        [
                            abjad.Momento(
                                context='Contrabass_I_Music_Voice',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='Cb. I',
                                ),
                            abjad.Momento(
                                context='Contrabass_I_Music_Voice',
                                manifest='instruments',
                                value='Contrabass',
                                ),
                            abjad.Momento(
                                context='Contrabass_I_Music_Voice',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='Contrabass_I_Music_Voice',
                                prototype='baca.StaffLines',
                                value=5,
                                ),
                            ],
                        ),
                    (
                        'Contrabass_I_Music_Voice',
                        [
                            abjad.Momento(
                                context='Contrabass_I_Music_Voice',
                                prototype='abjad.Dynamic',
                                value='p',
                                ),
                            ],
                        ),
                    (
                        'Harp_Music_Staff',
                        [
                            abjad.Momento(
                                context='Harp_Music_Voice',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='Hp.',
                                ),
                            abjad.Momento(
                                context='Harp_Music_Voice',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            abjad.Momento(
                                context='Harp_Music_Voice',
                                prototype='baca.StaffLines',
                                value=5,
                                ),
                            ],
                        ),
                    (
                        'Harp_Music_Voice',
                        [
                            abjad.Momento(
                                context='Harp_Music_Voice',
                                prototype='abjad.Dynamic',
                                value='mp',
                                ),
                            ],
                        ),
                    (
                        'Percussion_II_Music_Staff',
                        [
                            abjad.Momento(
                                context='Percussion_II_Music_Voice',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='Perc. II',
                                ),
                            abjad.Momento(
                                context='Percussion_II_Music_Voice',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='Percussion_II_Music_Voice',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='Percussion_II_Music_Voice',
                                prototype='baca.StaffLines',
                                value=1,
                                ),
                            ],
                        ),
                    (
                        'Percussion_II_Music_Voice',
                        [
                            abjad.Momento(
                                context='Percussion_II_Music_Voice',
                                prototype='abjad.Dynamic',
                                value='mp',
                                ),
                            ],
                        ),
                    (
                        'Percussion_I_Music_Staff',
                        [
                            abjad.Momento(
                                context='Percussion_I_Music_Voice',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='Perc. I',
                                ),
                            abjad.Momento(
                                context='Percussion_I_Music_Voice',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='Percussion_I_Music_Voice',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='Percussion_I_Music_Voice',
                                prototype='baca.StaffLines',
                                value=3,
                                ),
                            ],
                        ),
                    (
                        'Percussion_I_Music_Voice',
                        [
                            abjad.Momento(
                                context='Percussion_I_Music_Voice',
                                prototype='abjad.Dynamic',
                                value='mp',
                                ),
                            ],
                        ),
                    (
                        'Percussion_Section_Staff_Group',
                        [
                            abjad.Momento(
                                context='Harp_Music_Voice',
                                manifest='instruments',
                                value='Harp',
                                ),
                            ],
                        ),
                    (
                        'Score',
                        [
                            abjad.Momento(
                                context='Global_Skips',
                                manifest='metronome_marks',
                                value='57 3/5',
                                ),
                            abjad.Momento(
                                context='Global_Skips',
                                prototype='abjad.TimeSignature',
                                value='4/4',
                                ),
                            ],
                        ),
                    (
                        'Viola_Music_Staff',
                        [
                            abjad.Momento(
                                context='Viola_Music_Voice',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='Va.',
                                ),
                            abjad.Momento(
                                context='Viola_Music_Voice',
                                manifest='instruments',
                                value='Viola',
                                ),
                            abjad.Momento(
                                context='Viola_Music_Voice',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            abjad.Momento(
                                context='Viola_Music_Voice',
                                prototype='baca.StaffLines',
                                value=5,
                                ),
                            ],
                        ),
                    (
                        'Viola_Music_Voice',
                        [
                            abjad.Momento(
                                context='Viola_Music_Voice',
                                prototype='abjad.Dynamic',
                                value='mp',
                                ),
                            ],
                        ),
                    ]
                ),
            ),
        ]
    )
