import baca


distances = [18, (32), (26, 26, 32), (26, 26, 26, 26, 32)]

breaks = baca.breaks(
    baca.page(
        baca.system(
            *[18, (26), (21, 21, 26), (21, 21, 21, 21, 26)],
            measure=1,
            y_offset=90,
            ),
        number=1,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=11,
            y_offset=40,
            ),
        number=2,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=21,
            y_offset=40,
            ),
        number=3,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=31,
            y_offset=40,
            ),
        number=4,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=41,
            y_offset=40,
            ),
        number=5,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=51,
            y_offset=40,
            ),
        number=6,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=61,
            y_offset=40,
            ),
        number=7,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=71,
            y_offset=40,
            ),
        number=8,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=81,
            y_offset=40,
            ),
        number=9,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=91,
            y_offset=40,
            ),
        number=10,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=101,
            y_offset=40,
            ),
        number=11,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=111,
            y_offset=40,
            ),
        number=12,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=121,
            y_offset=40,
            ),
        number=13,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=131,
            y_offset=40,
            ),
        number=14,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=141,
            y_offset=40,
            ),
        number=15,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=151,
            y_offset=40,
            ),
        number=16,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=161,
            y_offset=40,
            ),
        number=17,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=171,
            y_offset=40,
            ),
        number=18,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=181,
            y_offset=40,
            ),
        number=19,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=191,
            y_offset=40,
            ),
        number=20,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=201,
            y_offset=40,
            ),
        number=21,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=211,
            y_offset=40,
            ),
        number=22,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=221,
            y_offset=40,
            ),
        number=23,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=231,
            y_offset=40,
            ),
        number=24,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=241,
            y_offset=40,
            ),
        number=25,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=251,
            y_offset=40,
            ),
        number=26,
        ),
    baca.page(
        baca.system(
            *distances,
            measure=261,
            y_offset=40,
            ),
        number=27,
        ),
    )
    
spacing = baca.scorewide_spacing(
    __file__,
    breaks=breaks,
    fallback_duration=(1, 32),
    )
