import baca


distances = [20, (34), (31, 31, 34), (31, 31, 31, 31, 34)]

breaks = baca.breaks(
    baca.page(
        baca.system(
            *[22, (28), (25, 25, 28), (25, 25, 25, 25, 28)],
            measure=1,
            y_offset=90,
        ),
        number=1,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=5,
            y_offset=32,
        ),
        number=2,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=9,
            y_offset=32,
        ),
        number=3,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=13,
            y_offset=32,
        ),
        number=4,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=17,
            y_offset=32,
        ),
        number=5,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=21,
            y_offset=32,
        ),
        number=6,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=25,
            y_offset=32,
        ),
        number=7,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=29,
            y_offset=32,
        ),
        number=8,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=33,
            y_offset=32,
        ),
        number=9,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=37,
            y_offset=32,
        ),
        number=10,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=41,
            y_offset=32,
        ),
        number=11,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=45,
            y_offset=32,
        ),
        number=12,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=49,
            y_offset=32,
        ),
        number=13,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=53,
            y_offset=32,
        ),
        number=14,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=57,
            y_offset=32,
        ),
        number=15,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=61,
            y_offset=32,
        ),
        number=16,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=65,
            y_offset=32,
        ),
        number=17,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=69,
            y_offset=32,
        ),
        number=18,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=73,
            y_offset=32,
        ),
        number=19,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=77,
            y_offset=32,
        ),
        number=20,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=81,
            y_offset=32,
        ),
        number=21,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=85,
            y_offset=32,
        ),
        number=22,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=89,
            y_offset=32,
        ),
        number=23,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=93,
            y_offset=32,
        ),
        number=24,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=97,
            y_offset=32,
        ),
        number=25,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=101,
            y_offset=32,
        ),
        number=26,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=105,
            y_offset=32,
        ),
        number=27,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=109,
            y_offset=32,
        ),
        number=28,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=113,
            y_offset=32,
        ),
        number=29,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=117,
            y_offset=32,
        ),
        number=30,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=121,
            y_offset=32,
        ),
        number=31,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=125,
            y_offset=32,
        ),
        number=32,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=129,
            y_offset=32,
        ),
        number=33,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=133,
            y_offset=32,
        ),
        number=34,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=137,
            y_offset=32,
        ),
        number=35,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=141,
            y_offset=32,
        ),
        number=36,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=145,
            y_offset=32,
        ),
        number=37,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=149,
            y_offset=32,
        ),
        number=38,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=153,
            y_offset=32,
        ),
        number=39,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=157,
            y_offset=32,
        ),
        number=40,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=161,
            y_offset=32,
        ),
        number=41,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=165,
            y_offset=32,
        ),
        number=42,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=169,
            y_offset=32,
        ),
        number=43,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=173,
            y_offset=32,
        ),
        number=44,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=177,
            y_offset=32,
        ),
        number=45,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=181,
            y_offset=32,
        ),
        number=46,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=185,
            y_offset=32,
        ),
        number=47,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=189,
            y_offset=32,
        ),
        number=48,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=193,
            y_offset=32,
        ),
        number=49,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=197,
            y_offset=32,
        ),
        number=50,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=201,
            y_offset=32,
        ),
        number=51,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=205,
            y_offset=32,
        ),
        number=52,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=209,
            y_offset=32,
        ),
        number=53,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=213,
            y_offset=32,
        ),
        number=54,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=217,
            y_offset=32,
        ),
        number=55,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=221,
            y_offset=32,
        ),
        number=56,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=225,
            y_offset=32,
        ),
        number=57,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=229,
            y_offset=32,
        ),
        number=58,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=233,
            y_offset=32,
        ),
        number=59,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=237,
            y_offset=32,
        ),
        number=60,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=241,
            y_offset=32,
        ),
        number=61,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=245,
            y_offset=32,
        ),
        number=62,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=249,
            y_offset=32,
        ),
        number=63,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=253,
            y_offset=32,
        ),
        number=64,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=254,
            y_offset=32,
        ),
        number=65,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=259,
            y_offset=32,
        ),
        number=66,
    ),
    baca.page(
        baca.system(
            *distances,
            measure=263,
            y_offset=32,
        ),
        number=67,
    ),
)
    
spacing = baca.scorewide_spacing(
    __file__,
    breaks=breaks,
    fallback_duration=(1, 40),
)

text_measure_numbers = [
    15, 18, 20, 41, 48, 57, 69, 82, 91, 97, 107, 115, 119,
    122, 129, 156, 163, 170, 177, 193, 206, 229, 236, 239, 248, 254,
    261, 268,
    ]
spacing.override(text_measure_numbers, (1, 288), fermata=True)

#spacing.override((21, 26), (1, 32))
#spacing.override((49, 56), (1, 20))
#spacing.override((113, 114), (1, 20))
#spacing.override((116, 118), (1, 20))
#spacing.override((171, 176), (1, 20))
#spacing.override([191, 192, 194, 195], (1, 32))
